meta_product_name: "EA Oxford Conversations"
meta_title: "EA Oxford Conversations - Talk about interesting and important things"
meta_description: "EA Oxford Conversations is where you can submit topics that you'd be interested in talking about with others, and get linked up with people who want to talk about that thing."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
